services:
  hiveui:
    image: ghcr.io/bdevt/hiveui:latest
    pull_policy: always    
    ports:
      - "3000:3000"
    environment:
      - AUTH_SECRET
      - AUTH_KEYCLOAK_ID
      - AUTH_KEYCLOAK_SECRET
      - AUTH_KEYCLOAK_ISSUER
      - PUBLIC_ROOT_FOLDER_LOCATION
    restart: unless-stopped